-- Edge-Types
CREATE ELABEL located;
CREATE ELABEL serves;
CREATE ELABEL belongs_to;
CREATE ELABEL follows;
CREATE ELABEL controls;
CREATE ELABEL lives_in;
CREATE ELABEL member_of;
CREATE ELABEL related;
CREATE ELABEL knows;
CREATE ELABEL take_part;
CREATE ELABEL from;
CREATE ELABEL to;
