-- Node-Types
CREATE VLABEL sovereign_entity;
CREATE VLABEL continent;
CREATE VLABEL country;
CREATE VLABEL town;
CREATE VLABEL place;
CREATE VLABEL force;
CREATE VLABEL "order";
CREATE VLABEL dynasty;
CREATE VLABEL person;
CREATE VLABEL event;
CREATE VLABEL artifact;
CREATE VLABEL book;
CREATE VLABEL religion;
CREATE VLABEL philosophy;
